name: medics
description: "A new Flutter project."

publish_to: 'none' 

version: 1.1.1+18

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  
  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  flutter_iconly: ^1.0.2

  # Utility
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.2.4
  flutter_native_splash: ^2.3.7
  responsive_sizer: ^3.1.1
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^5.0.0
  change_app_package_name: ^1.4.0
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0
  google_sign_in: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_widget_from_html: ^0.15.2
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  # android_alarm_manager_plus: ^4.0.4
  permission_handler: ^11.3.1
  lottie: ^3.1.3
  # auto_start_flutter: ^0.1.1
  alarm: ^4.0.9
  shimmer: ^3.0.0

  # State Management
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  #  flutter_background: ^1.3.0+1
  #  android_intent_plus: ^5.2.0
  flutter_background_service: ^5.0.10
  # flutter_native_splash: ^2.4.2
  disable_battery_optimization: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/sounds/

  fonts:
    - family: "OpenSans"
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
